[phases.setup]
nixPkgs = ["python312", "libGL", "glib", "fontconfig", "freetype"]

[phases.install]
cmds = ["python3.12 -m ensurepip", "python3.12 -m pip install --upgrade pip", "python3.12 -m pip install -r requirements.txt"]

[start]
cmd = "python3.12 app.py"
